options:
  source:
    type: string
    default:
    description: |
      Repository from which to install LXD.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported release pocket
  block-device:
    type: string
    default:
    description: |
       Device to be used to back LXD storage. May be an valid block
       device or a path and size to a local file (/path/to/file.img|$sizeG),
       which will be created and used as a loopback device (for testing only).
       .
       This will be use to store lxd containers.
  overwrite:
    default: False
    type: boolean
    description: |
      If enabled, the charm will attempt to overwrite block devices
      containing previous filesystems or LVM, assuming it is not in use.
  storage-type:
    type: string
    default: btrfs
    description: |
       LXD container storage type: btrfs, zfs, or lvm
  ephemeral-unmount:
    type: string
    default:
    description: |
      Cloud instances provide ephemeral storage which is normally mounted
      on /mnt.
      .
      Providing this option will force an unmount of the ephemeral device
      so that it can be used for LXD container storage.  This is useful for
      testing purposes (cloud deployment is not a typical use case).
  use-source:
    type: boolean
    default: False
    description: Use LXD source from github.

